In [1]:
import pickle
with open('knn_model.pickle','rb') as f:
  knn_new = pickle.load(f)

In [2]:
import pickle
with open('scaler.pickle','rb') as f:
  scaler_new = pickle.load(f)

In [3]:
import pandas as pd
new_df = pd.read_csv("https://raw.githubusercontent.com/futurexskill/projects/main/knn-classification/new_customers.csv")

In [4]:
len(new_df)

10

In [5]:
gender_encoded_new = pd.get_dummies(new_df['Gender'], drop_first=True)

In [6]:
gender_encoded_new

Male
0   True
1  False
2   True
3   True
4   True
5   True
6  False
7   True
8  False
9   True

In [7]:
df_new_2 = pd.concat([new_df,gender_encoded_new],axis=1)

In [8]:
df_new_2

Gender  Age  Salary  Product ID  Price   Male
0    Male   24   38652           3   4446   True
1  Female   47   64727           1   5188  False
2    Male   46   54648           1   6193   True
3    Male   31   20018           3   4779   True
4    Male   58   77731           2   6855   True
5    Male   28   55478           1   6153   True
6  Female   48   54211           2   7588  False
7    Male   31   60076           3   5238   True
8  Female   42   29290           1   5418  False
9    Male   50   21445           1   5598   True

In [11]:
x_new = df_new_2[['Male','Age','Salary','Price']].to_numpy()

In [12]:
x_new

array([[True, 24, 38652, 4446],
       [False, 47, 64727, 5188],
       [True, 46, 54648, 6193],
       [True, 31, 20018, 4779],
       [True, 58, 77731, 6855],
       [True, 28, 55478, 6153],
       [False, 48, 54211, 7588],
       [True, 31, 60076, 5238],
       [False, 42, 29290, 5418],
       [True, 50, 21445, 5598]], dtype=object)

In [13]:
x_new_scale2 = scaler_new.fit_transform(x_new)

In [14]:
x_new_scale2

array([[ 0.65465367, -1.54774434, -0.48875298, -1.42543997],
       [-1.52752523,  0.60971747,  0.93112246, -0.61159228],
       [ 0.65465367,  0.51591478,  0.38228547,  0.49072164],
       [ 0.65465367, -0.89112553, -1.50343981, -1.06019565],
       [ 0.65465367,  1.64154703,  1.63923599,  1.21682294],
       [ 0.65465367, -1.17253359,  0.42748189,  0.44684845],
       [-1.52752523,  0.70352015,  0.35848928,  2.02079916],
       [ 0.65465367, -0.89112553,  0.67785916, -0.55675079],
       [-1.52752523,  0.14070403, -0.99854681, -0.35932143],
       [ 0.65465367,  0.89112553, -1.42573465, -0.16189207]])

In [15]:
y_new_pred = knn_new.predict(x_new_scale2)

In [16]:
y_new_pred

array([0, 1, 1, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [17]:
df_new_2['will_purchase'] = y_new_pred

In [18]:
df_new_2

Gender  Age  Salary  Product ID  Price   Male  will_purchase
0    Male   24   38652           3   4446   True              0
1  Female   47   64727           1   5188  False              1
2    Male   46   54648           1   6193   True              1
3    Male   31   20018           3   4779   True              0
4    Male   58   77731           2   6855   True              0
5    Male   28   55478           1   6153   True              1
6  Female   48   54211           2   7588  False              0
7    Male   31   60076           3   5238   True              0
8  Female   42   29290           1   5418  False              0
9    Male   50   21445           1   5598   True              0

In [19]:
df_new_2.to_csv("Model_predictions.csv",index=False)